### ISSUE TITLE
Cannot install RevEcoR locally

### ISSUE THREAD

**Issue by Starfishgames** [yiluheihei/RevEcoR#2]
Hello,
I'm trying to install your software, but R refuses to do it. Instead, it gives me the following error:

> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘Rcpp’

How can this be fixed?

**Comment by yiluheihei** [comment]
sorry for  the late response
